### ISSUE TITLE
Can this method be used for super-resolution

### ISSUE THREAD

**Issue by pmj110119** [edongdongchen/REI#1]
Thanks for your code！

Can this method be used for noise reduction and super-resolution of noisy images collected by imaging equipment?

**Comment by edongdongchen** [comment]
> 

Hello! Yes, surely the (robust) equivariant imaging can be used to learn high-resolution images from their noisy and low-resolution measurement images. Have a check your SR degradation model (e.g. blur kernel, downsampling and statistics of noise) and identify which kind of group actions you could apply.

**Comment by pmj110119** [comment]
Please forgive me for my shallow understanding of this task...

If I want to do noise reduction or super-resolution tasks, how can I design A and A_dagger?

**Comment by edongdongchen** [comment]
> Please forgive me for my shallow understanding of this task...
> 
> If I want to do noise reduction or super-resolution tasks, how can I design A and A_dagger?

No worries. For the SR example, it means the sensing model A (e.g. 4x downsampling) and the noise model (e.g. Gaussian) are known or can be estimated. A_dagger could be approximated by e.g. Bicubic interpolation - which is cheap and easy to calculate.
