### ISSUE TITLE
About the supplementary material

### ISSUE THREAD

**Issue by XiaoqiangZhou** [edongdongchen/REI#2]
Thanks for sharing such a great work. I think equivariant imaging is a very interesting idea and notice your previous work in this field.

I have some questions about the experimental details and derivations. Could you please share with me the  supplementary material of this paper? A public link or emailing to xq525@mail.ustc.edu.cn are both ok.

Thanks.

**Comment by edongdongchen** [comment]
> Thanks for sharing such a great work. I think equivariant imaging is a very interesting idea and notice your previous work in this field.
> 
> I have some questions about the experimental details and derivations. Could you please share with me the supplementary material of this paper? A public link or emailing to [xq525@mail.ustc.edu.cn](mailto:xq525@mail.ustc.edu.cn) are both ok.
> 
> Thanks.

Surely thing!

Please find the public link to [supp] at https://openaccess.thecvf.com/content/CVPR2022/html/Chen_Robust_Equivariant_Imaging_A_Fully_Unsupervised_Framework_for_Learning_To_CVPR_2022_paper.html

while you can also find them in our latest arXiv version:
https://arxiv.org/pdf/2111.12855.pdf

All the best

**Comment by XiaoqiangZhou** [comment]
Thanks for your quick reply!
